import 'GridModeller.dart';

List<AdayCarilerGridModel> adayCarilerGridList = [];
List<AlislarGridModel> alislarGridList = [];
List<CariEkstreGridModel> cariEkstreGridList = [];
List<CarilerGridModel> carilerGridList = [];
List<RiskFoyuGridModel> riskFoyuGridList = [];
List<DonemselBakiyelerGridModel> donemselBakiyelerGridList = [];
List<DovizKurlariGridModel> dovizKurlariGridList = [];
List<OrtalamaVadeGridModel> ortalamaVadeGridList = [];
List<PortfoydekiCeklerGridModel> portfoydekiCeklerGridList = [];
List<ButceGerceklesenRapor> butceGerceklesenRaporGridList = [];
List<SatislarGridModel> satislarGridList = [];
List<ZiyaretlerGridModel> ziyaretlerGridList = [];
List<StoklarGridModel> stoklarGridList = [];
List<StokFiyatlariGridModel> stokFiyatlariGridList = [];
List<StokReferanslariGridModel> stokReferanslariGridList = [];
List<StokKimlereSatilmisGridModel> stokKimlereSatilmisGridList = [];
List<StokKimlerdenAlinmisGridModel> stokKimlerdenAlinmisGridList = [];
List<StokAlternatifleriGridModel> stokAlternatifleriGridList = [];
List<PortalTalepleriGridModel> portalTalepleriGridList = [];
List<TahsilatlarGridModel> tahsilatlarGridList = [];
List<SatisTahsilatlarAnaliziGridModel> satisTahsilatlarAnaliziGridList = [];
List<SatisTahsilatTemsilciModel> satisTahsilatTemsilciGridList = [];
List<SatisTahsilatOzetGridModel> satisTahsilatOzetGridList = [];
List<TahsilatBakiyeAnaliziGridModel> tahsilatBakiyeAnaliziGridList = [];
List<CiroTablosuGridModel> ciroTablosuGridList = [];
List<StokSatisKarlilikRaporuGridModel> stokSatisKarlilikRaporuGridList = [];
List<OnlineHesabimGridModel> onlineHesabimGridList = [];
List<ZiyaretPlaniGridModel> ziyaretPlaniGridList = [];
List<AcikSiparislerGridModel> acikSiparisGridList = [];
List<TumAcikSiparislerGridModel> tumAcikSiparisGridList=[];
List<DepoDetayGridModel> depoMiktarlariGridList = [];
List<SatisCiroKaybiGridModel> satisCiroKaybiGridList = [];
List<OrtalamaVadeHesapla> ovhGridList = [];

List cariAutoComplateList = [];
List stokAutoComplateList = [];
